_commit: v1.12.1-10-g6796849
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: f1.yaml,pager-duty.yaml,wimbledon.yaml,wrexham.yaml
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: 'app: calendar-sync'
name: calendar-sync
namespace: calendar-sync
pvc: false
reloader: true
resources: []
service: false
serviceAccount: false
upstreamURL: https://github.com/magicdude4eva/calendar-sync
url: https://github.com/charlesthomas/homelab-calendar-sync
